shared:
  vault_addr: <%= ENV["VAULT_ADDR"] %>
  vault_token: <%= ENV["VAULT_TOKEN"] %>
  # Pre-existing root CA in Vault for signing intermediate created by astral
  vault_root_ca_ref: <%= ENV["VAULT_ROOT_CA_REF"] || "root-ca" %>
  vault_root_ca_mount: <%= ENV["VAULT_ROOT_CA_MOUNT"] || "pki" %>

  jwt_signing_key: <%= ENV["JWT_SIGNING_KEY"] %>
  cert_ttl: <%= ENV["CERT_TTL"] %>

  app_registry_addr: <%= ENV["APP_REGISTRY_ADDR"] %>
  app_registry_token: <%= ENV["APP_REGISTRY_TOKEN"] %>
  app_registry_ca_file: <%= ENV["APP_REGISTRY_CA_FILE"] %>
  app_registry_client_cert: <%= ENV["APP_REGISTRY_CLIENT_CERT"] %>
  app_registry_client_key: <%= ENV["APP_REGISTRY_CLIENT_KEY"] %>

  audit_log_file: <%= ENV["AUDIT_LOG_FILE"] || "#{Rails.root.join('log')}/astral-audit.log" %>

test:
  cert_ttl: <%= 24.hours.in_seconds %>

development:

production:
