shared:
  vault_addr: 
  vault_token:

  # Pre-existing root CA, or create new if requested
  vault_create_root: true
  vault_root_ca_ref: root_ca
  vault_root_ca_mount: pki_root

  jwt_signing_key:
  cert_ttl:

  app_registry_addr:
  app_registry_token:
  app_registry_ca_file:
  app_registry_client_cert:
  app_registry_client_key:

  audit_log_file: <%= "#{Rails.root.join('log')}/astral-audit.log" %>

test:
  configure_oidc?: true
  oidc_provider:
    name: "identity/oidc/provider/my-provider"
    host: "http://oidc_provider:8300"
  initial_user:
    name: "test"
    password: "test"
    email: "test@example.com"
  cert_ttl: <%= 24.hours.in_seconds %>

development:
  configure_oidc?: true
  oidc_provider:
    name: "identity/oidc/provider/my-provider"
    host: "http://oidc_provider:8300"
  initial_user:
    name: "test"
    password: "test"
    email: "test@example.com"

production:
  vault_create_root: false
