shared:
  vault_addr: 
  vault_token:

  # Pre-existing root CA, or create new if requested
  vault_create_root: true
  vault_root_ca_ref: root_ca
  vault_root_ca_mount: pki_root

  jwt_signing_key:
  cert_ttl:

  app_registry_addr:
  app_registry_token:
  app_registry_ca_file:
  app_registry_client_cert:
  app_registry_client_key:

  audit_log_file: <%= "#{Rails.root.join('log')}/astral-audit.log" %>

  oidc_issuer:
  oidc_client_id:
  oidc_client_secret:
  oidc_redirect_uris: http://localhost:8250/oidc/callback
  oidc_provider_addr: http://oidc_provider:8300
  oidc_issuer: http://oidc_provider:8300/v1/identity/oidc/provider/astral

  initial_user_name: test
  initial_user_password: test
  initial_user_email: test@example.com

test:
  cert_ttl: <%= 24.hours.in_seconds %>

development:

production:
  vault_create_root: false

  oidc_provider_addr:
  oidc_issuer:

  initial_user_name:
  initial_user_password:
  initial_user_email:

