shared:
  vault_addr: <%= ENV["VAULT_ADDR"] %>
  vault_token: <%= ENV["VAULT_TOKEN"] %>
  vault_cert_path: "pki_int/issue/learn"
  jwt_signing_key: <%= ENV["JWT_SIGNING_KEY"] %>
  cert_ttl: <%= ENV["CERT_TTL"] %>

test:
  cert_ttl: <%= 24.hours.in_seconds %>

development:

production:
