name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build_test: # all steps run in dev container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: |
            # Add multiple commands to run if needed
            bundle install

      - name: Lint code for consistent style
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: bin/rubocop -f github
  
      - name: Run brakeman
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: bin/brakeman --no-pager

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: bin/rails test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
